Repository sebiny/6-moving-team2-FE, pull requests merged in 2025-07, with the labels that each got.

#1 파일구조셋팅
  .github/pull_request_template.md
  .gitignore
  README.md
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/favicon.ico
  public/file.svg
  public/fonts/.gitkeep
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(main)/.gitkeep
  src/app/(protected)/driver/.gitkeep
  src/app/(protected)/member/.gitkeep
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/diver/.gitkeep
  src/app/login/member/.gitkeep
  src/app/page.tsx
  src/app/signup/driver/.gitkeep
  src/app/signup/member/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/hooks/.gitkeep
  src/lib/api/api-1.ts
  src/lib/api/api-2.ts
  src/lib/api/api-3.ts
  src/lib/api/utils/.gitkeep
  src/lib/fetchClient.ts
  src/middleware.ts
  src/providers/AuthProvider.tsx
  src/providers/providers.tsx
  tsconfig.json
Labels: Chore

#3 [UI] 기본 레이아웃, GNB 일부 제작
  package-lock.json
  package.json
  prettier.config.mjs
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/app/common/page.tsx
  src/app/globals.css
  src/app/landing/layout.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/.gitkeep
  src/components/container/PageContainer.tsx
  src/components/layout/Gnb.tsx
  src/components/layout/_components/Logo.tsx
Labels: FE, UI

#5 [UI] gnb 컴포넌트 제작
  src/components/dropdown/NotificationDropdown.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/layout/Gnb.tsx
  src/components/layout/_components/Logo.tsx
  src/components/list/GnbList.tsx
  src/constant/constant.ts
Labels: FE, UI

#9 chore:폴더구조 파일이름 변경
  src/app/(auth)/login/diver/.gitkeep
  src/app/(auth)/login/member/.gitkeep
  src/app/(auth)/signup/driver/.gitkeep
  src/app/(auth)/signup/member/.gitkeep
  src/app/(guest)/drivers/[id]/_components/ ShareDriver.tsx
  src/app/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/(guest)/drivers/[id]/_components/Review.tsx
  src/app/(guest)/drivers/[id]/_components/Reviews.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/_components/DriverSimpleInfo.tsx
  src/app/(guest)/drivers/_components/LikedDriverInfo.tsx
  src/app/(guest)/drivers/_components/LikedDrivers.tsx
  src/app/(guest)/drivers/page.tsx
  src/app/review/component/Main.tsx
Labels: Chore

#11 [UI] 공통 컴포넌트
  package-lock.json
  package.json
  src/app/(guest)/drivers/[id]/_components/EstimateRequestModal.tsx
  src/app/(guest)/drivers/[id]/_components/Reviews.tsx
  src/app/(guest)/drivers/[id]/_components/ShareDriver.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/_components/DriverSimpleInfo.tsx
  src/app/(guest)/drivers/_components/LikedDriverInfo.tsx
  src/app/(guest)/drivers/page.tsx
  src/app/common/page.tsx
  src/components/ChipCircle.tsx
Labels: Feature, UI

#16 [UI] review UI main 부분 제작 중
  src/app/review/component/Header.tsx
  src/app/review/component/Main.tsx
  src/app/review/page.tsx
  src/components/layout/Gnb.tsx
Labels: Feature, FE, UI

#18 [김다은] 대기중인 견적 페이지 작업 중 버셀 배포 해결 위한 1차 pr
  package.json
  src/app/(protected)/driver/pending-card/PendingCard.tsx
  src/app/(protected)/driver/pending-card/PendingData.ts
  src/app/(protected)/member/estimate-pending/_components/EstimateSubHeader.tsx
  src/app/(protected)/member/estimate-pending/_components/PendingCard.tsx
  src/app/(protected)/member/estimate-pending/page.tsx
Labels: Fix, FE, UI

#17 [기능] 이사유형 칩 컴포넌트 구현
  src/app/common/page.tsx
  src/components/chip/ChipRectangle.tsx
  src/constant/moveTypes.ts
  tsconfig.json
Labels: Feature, FE

#24 [김다은] 대기중인 견적 페이지 ui 완성
  package.json
  src/app/(protected)/member/estimate-pending/_components/EstimateSubHeader.tsx
  src/app/(protected)/member/estimate-pending/_components/PendingCard.tsx
  src/app/(protected)/member/estimate-pending/page.tsx
  tailwind.config.mjs
Labels: FE, UI

#27 [UI] 기사님 상세페이지 반응형 추가
  public/assets/icons/ic_drawing.svg
  public/assets/icons/ic_like_black.svg
  src/app/(guest)/drivers/[id]/_components/BottomButton.tsx
  src/app/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/_components/DriverSimpleInfo.tsx
  src/app/(guest)/drivers/_components/Filters.tsx
  src/app/(guest)/drivers/_components/LikedDriverInfo.tsx
  src/app/(guest)/drivers/page.tsx
  src/app/(protected)/driver/my-page/page.tsx
  src/app/common/page.tsx
  src/components/Button.tsx
  src/components/OrangeBackground.tsx
  src/components/Service.tsx
  src/components/ShareDriver.tsx
  src/components/icon/LikeIcon.tsx
  src/components/icon/StarIcon.tsx
  src/components/icon/WritingIcon.tsx
  src/constant/driverType.ts
Labels: Feature, UI

#29 [UI] review UI 제작 중 (pagination컴포넌트, 내가 작성한 리뷰, 작성가능한리뷰 )
  public/assets/icons/ic_chevron_right_black.svg
  src/app/review/component/Main.tsx
  src/app/review/component/Modal.tsx
  src/app/review/component/MyReviews.tsx
  src/app/review/component/Pagination.tsx
  src/app/review/component/ReviewModal.tsx
  src/app/review/component/Reviews.tsx
  src/app/review/page.tsx
  src/components/Header.tsx
  src/components/Pagination.tsx
Labels: Feature, FE, UI

#31 [김다은] 받았던 견적 페이지 ui & title 수정
  src/app/(protected)/member/estimate-past/_components/EstimateDetail.tsx
  src/app/(protected)/member/estimate-past/_components/ReceivedEstimate.tsx
  src/app/(protected)/member/estimate-past/page.tsx
  src/app/common/page.tsx
  src/components/title/Title.tsx
  src/components/title/TitleData.ts
Labels: Fix, FE, UI

#33 feat: 게스트, 컴포넌트 관련 라우트 추가
  src/components/DevNav.tsx
Labels: FE, UI

#34 [김다은] 배포 에러 해결
  src/app/(protected)/member/estimate-pending/_components/PendingCard.tsx
Labels: Fix

#35 feat: 견적 요청 페이지 UI 및 반응형 구조 구현
  public/assets/images/img_moving_car.png
  src/app/(protected)/member/estimate-request/DesktopEstimateForm.tsx
  src/app/(protected)/member/estimate-request/DisabledForm.tsx
  src/app/(protected)/member/estimate-request/MobileEstimateForm.tsx
  src/app/(protected)/member/estimate-request/_components/AddressCardModal.tsx
  src/app/(protected)/member/estimate-request/_components/AddressResultCard.tsx
  src/app/(protected)/member/estimate-request/_components/CalenderDropdown.tsx
  src/app/(protected)/member/estimate-request/_components/DatePicker.tsx
  src/app/(protected)/member/estimate-request/_components/MobileDatePicker.tsx
  src/app/(protected)/member/estimate-request/_components/MoveTypeCard.tsx
  src/app/(protected)/member/estimate-request/page.tsx
  src/hooks/.gitkeep
  src/hooks/useMediaQuery.ts
Labels: FE, UI

#36 [FIX] MoveType 소문자에서 대문자로 변경
  src/app/(guest)/drivers/[id]/_components/BottomButton.tsx
  src/app/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/(guest)/drivers/[id]/_components/RequestEstimate.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/_components/LikedDriverInfo.tsx
  src/app/(guest)/drivers/page.tsx
  src/app/(protected)/driver/my-page/page.tsx
  src/app/(protected)/member/estimate-past/_components/ReceivedEstimate.tsx
  src/app/(protected)/member/estimate-pending/_components/PendingCard.tsx
  src/app/common/page.tsx
  src/app/review/component/MyReviews.tsx
  src/app/review/component/Reviews.tsx
  src/components/Button.tsx
  src/components/Service.tsx
  src/components/ShareDriver.tsx
  src/components/card/DriverFindCard.tsx
  src/components/chip/ChipRectangle.tsx
  src/components/driver/Review.tsx
  src/components/driver/Reviews.tsx
  src/components/title/Title.tsx
  src/components/title/TitleData.ts
  src/constant/driverType.ts
  src/constant/moveTypes.ts
  src/utills/TranslateFunction.tsx
Labels: Fix, UI

#38 [UI] review 모달 제작중(Desktop version)
  src/app/review/component/ReviewModal.tsx
  src/components/InputText.tsx
Labels: Feature, FE, UI

#37 [UI] 전체 layout에 gnb 적용
  src/app/landing/layout.tsx
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/review/page.tsx
  src/components/layout/Gnb.tsx
  src/components/list/GnbList.tsx
  src/constant/constant.ts
Labels: FE, UI

#41 [김다은] Title + 내견적관리 페이지들 전체적인 수정 -> 빌드에러 포함 충돌 해결
  src/app/(protected)/member/my-estimates/estimate-past/PastEstimates.tsx
  src/app/(protected)/member/my-estimates/estimate-past/_components/EstimateDetail.tsx
  src/app/(protected)/member/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
  src/app/(protected)/member/my-estimates/estimate-past/_components/ReceivedEstimateData.ts
  src/app/(protected)/member/my-estimates/estimate-past/page.tsx
  src/app/(protected)/member/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/(protected)/member/my-estimates/estimate-pending/_components/EstimateSubHeader.tsx
  src/app/(protected)/member/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/app/(protected)/member/my-estimates/estimate-pending/_components/PendingData.ts
  src/app/(protected)/member/my-estimates/estimate-pending/page.tsx
  src/app/(protected)/member/my-estimates/page.tsx
  src/app/common/page.tsx
  src/components/DevNav.tsx
  src/components/Title.tsx
  src/components/chip/EstimateStatus.tsx
  src/components/title/LabelIcons.ts
  src/components/title/TitleData.ts
Labels: Fix, FE, UI

#42 [UI] 기사님 마이페이지 반응형 추가
  package-lock.json
  package.json
  src/app/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/(guest)/drivers/[id]/_components/Toast.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(protected)/driver/my-page/page.tsx
  src/components/OrangeBackground.tsx
  src/components/ShareDriver.tsx
  src/components/driver/DriverReview.tsx
  src/components/driver/DriverReviews.tsx
  src/components/driver/DriverSimpleInfo.tsx
  src/constant/reviewType.ts
  src/utills/ReviewAverage.tsx
Labels: Feature, UI

#43 Feature/estimate request
  src/app/(protected)/member/estimate-request/DesktopEstimateForm.tsx
  src/app/(protected)/member/estimate-request/DisabledForm.tsx
  src/app/(protected)/member/estimate-request/MobileEstimateForm.tsx
  src/app/(protected)/member/estimate-request/_components/AddressCardModal.tsx
  src/app/(protected)/member/estimate-request/_components/DatePicker.tsx
  src/app/(protected)/member/estimate-request/_components/MobileDatePicker.tsx
  src/app/(protected)/member/estimate-request/page.tsx
  src/utills/AddressSummary.tsx
  src/utills/dateUtils.tsx
Labels: Refactor, FE, UI

#44 [UI] 리뷰 생성 UI 작업 중 (유효성 검사 작업 중)
  public/assets/icons/ic_X_gray.svg
  src/app/review/component/Main.tsx
  src/app/review/component/ModalContent.tsx
  src/app/review/component/MyReviews.tsx
  src/app/review/component/ReviewModal.tsx
  src/app/review/component/ReviewWrite.tsx
  src/app/review/component/Reviews.tsx
  src/app/review/page.tsx
  src/components/InputText.tsx
  src/constant/moveDetails.ts
Labels: Feature, FE, UI

#48 [Feat, 이지수] 전역 인증 및 인증 API 전역 라우팅 기능 추가, member →customer 폴더 이름 수정
  src/app/(auth)/login/customer/page.tsx
  src/app/(auth)/login/diver/.gitkeep
  src/app/(auth)/login/driver/page.tsx
  src/app/(auth)/login/member/.gitkeep
  src/app/(auth)/signup/customer/page.tsx
  src/app/(auth)/signup/driver/.gitkeep
  src/app/(auth)/signup/driver/page.tsx
  src/app/(auth)/signup/member/.gitkeep
  src/app/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/(protected)/customer/estimate-request/DisabledForm.tsx
  src/app/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/(protected)/customer/estimate-request/_components/AddressCardModal.tsx
  src/app/(protected)/customer/estimate-request/_components/AddressResultCard.tsx
  src/app/(protected)/customer/estimate-request/_components/CalenderDropdown.tsx
  src/app/(protected)/customer/estimate-request/_components/DatePicker.tsx
  src/app/(protected)/customer/estimate-request/_components/MobileDatePicker.tsx
  src/app/(protected)/customer/estimate-request/_components/MoveTypeCard.tsx
  src/app/(protected)/customer/estimate-request/page.tsx
  src/app/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
  src/app/(protected)/customer/my-estimates/estimate-past/_components/EstimateDetail.tsx
  src/app/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
  src/app/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimateData.ts
  src/app/(protected)/customer/my-estimates/estimate-past/page.tsx
  src/app/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/(protected)/customer/my-estimates/estimate-pending/_components/EstimateSubHeader.tsx
  src/app/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/app/(protected)/customer/my-estimates/estimate-pending/_components/PendingData.ts
  src/app/(protected)/customer/my-estimates/estimate-pending/page.tsx
  src/app/(protected)/customer/my-estimates/page.tsx
  src/app/layout.tsx
  src/components/DevNav.tsx
  src/hooks/UseAuthForm.ts
  src/lib/api/api-1.ts
  src/lib/api/api-auth.ts
  src/lib/api/utils/.gitkeep
  src/lib/fetch-client.ts
  src/lib/fetchClient.ts
  src/lib/utils/error-parser.ts
  src/middleware.ts
  src/providers/AuthProvider.tsx
  src/providers/Providers.tsx
  src/providers/providers.tsx
  src/types/UserType.ts
Labels: Feature

#50 [기능] 기사님 받은요청 페이지 및 카드 UI 컴포넌트 구현
  public/assets/icons/ic_frame.svg
  src/app/(protected)/driver/received-requests/_components/RequestCardList.tsx
  src/app/(protected)/driver/received-requests/page.tsx
  src/app/globals.css
  src/components/DevNav.tsx
  src/components/button/CustomCheckbox.tsx
  src/components/chip/ChipConfirmed.tsx
  src/components/driver/RequestCardBase.tsx
  src/components/input/SearchBar.tsx
  src/types/request.ts
Labels: Feature, FE, UI

#52 feat: gnb_menu 컴포넌트 제작, 로그인 여부에 따른 gnb 분기처리
  src/app/layout.tsx
  src/components/DevNav.tsx
  src/components/dropdown/NotificationDropdown.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/layout/Gnb.tsx
  src/components/layout/GnbListLayout.tsx
  src/components/list/GnbList.tsx
  src/components/list/GnbMenuList.tsx
  src/constant/constant.ts
  src/hooks/useGnbHook.ts
Labels: Feature, FE, UI

#54 feat: 카카오 우편번호 검색 기능 구현 및 모달 UI 연동
  package-lock.json
  package.json
  src/app/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/(protected)/customer/estimate-request/_components/AddressCardModal.tsx
  src/app/(protected)/customer/estimate-request/_components/DaumPostcodeModal.tsx
  src/types/Address.ts
Labels: Feature, FE, UI

#56 [FIX] 페이지 디자인 헤더에 맞게 수정
  src/app/(guest)/drivers/[id]/_components/Toast.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/page.tsx
  src/app/(protected)/driver/my-page/_components/EditButtons.tsx
  src/app/(protected)/driver/my-page/page.tsx
Labels: Fix, UI

#57 feat:작성가능한 리뷰 반응형 UI
  package-lock.json
  package.json
  src/app/review/component/Main.tsx
  src/app/review/component/ReviewCost.tsx
  src/app/review/component/Reviews.tsx
  src/app/review/component/ReviewsInner.tsx
  src/app/review/page.tsx
  src/hooks/useMediaHook.ts
Labels: FE, UI

#62 [feat 이지수] 프로필 생성 임시 페이지 추가 및 에러 메세지 기능 추가
  src/app/(auth)/login/customer/page.tsx
  src/app/(auth)/login/driver/page.tsx
  src/app/(auth)/signup/customer/page.tsx
  src/app/(auth)/signup/driver/page.tsx
  src/app/(protected)/customer/profile/page.tsx
  src/app/(protected)/driver/profile/page.tsx
  src/components/DevNav.tsx
  src/hooks/useAuthForm.ts
  src/lib/FetchClient.ts
  src/lib/api/api-auth.ts
  src/utills/ErrorParser.tsx
Labels: Feature

#63 [김다은] 상세 페이지 반응형 ui + 찜한 기사님 체크박스 수정
  src/app/(protected)/customer/my-estimates/_components/EstimateDetailInfo.tsx
  src/app/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
  src/app/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
  src/components/card/DriverFindCard.tsx
  src/constant/driverType.ts
Labels: FE, UI

#66 [기능] 확정 견적 칩, 이사완료 컴포넌트 및 관련 페이지 구현
  src/app/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/(protected)/driver/my-estimates/sent/_components/EstimateCardList.tsx
  src/app/(protected)/driver/my-estimates/sent/page.tsx
  src/app/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/app/(protected)/driver/received-requests/_components/RequestCardList.tsx
  src/app/(protected)/driver/received-requests/page.tsx
  src/components/Button.tsx
  src/components/DevNav.tsx
  src/components/Header.tsx
  src/components/chip/ChipConfirmed.tsx
Labels: FE, UI

#72 feature: 회원가입 알림
  package-lock.json
  package.json
  src/app/landing/layout.tsx
  src/app/layout.tsx
  src/components/dropdown/NotificationDropdown.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/gnb/Gnb.tsx
  src/components/gnb/GnbListLayout.tsx
  src/components/gnb/GnbMenuList.tsx
  src/components/gnb/_components/Logo.tsx
  src/lib/api/api-2.ts
  src/lib/api/api-notification.ts
  src/utills/dateUtils.tsx
Labels: Feature, FE

#74 프로필 userType에 따라 분기처리, route 수정
  src/components/dropdown/NotificationDropdown.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/constant/constant.ts
Labels: Fix, FE, UI

#75 fix: route 수정
  src/components/dropdown/ProfileDropdown.tsx
  src/constant/constant.ts
Labels: Fix, FE, UI

#77 기사님/프로필 드롭다운 메뉴 수정
  src/constant/constant.ts
Labels: FE, UI

#80 [FEAT] 기사님 상세 부분 리뷰 api 연결
  src/app/(guest)/drivers/[id]/_components/BottomButton.tsx
  src/app/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/(guest)/drivers/[id]/_components/FavoriteButton.tsx
  src/app/(guest)/drivers/[id]/_components/RequestEstimate.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/_components/Filters.tsx
  src/app/(guest)/drivers/_components/FindDrivers.tsx
  src/app/(guest)/drivers/_components/LikedDrivers.tsx
  src/app/(protected)/driver/my-page/page.tsx
  src/app/common/page.tsx
  src/app/review/component/Main.tsx
  src/components/Pagination.tsx
  src/components/Service.tsx
  src/components/card/DriverFindCard.tsx
  src/components/driver/DriverReview.tsx
  src/components/driver/DriverReviews.tsx
  src/constant/constant.ts
  src/constant/reviewType.ts
  src/lib/api/api-driver.ts
  src/lib/api/api-favorite.ts
  src/types/ServiceAreaType.ts
  src/types/driverType.ts
  src/types/reviewType.ts
  src/utills/ReviewAverage.tsx
  src/utills/ReviewRatio.tsx
Labels: Feature, FE, API

#83 [스타일] 주요 페이지 및 모달 반응형 스타일 적용
  src/app/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/(protected)/driver/my-estimates/sent/_components/EstimateCardList.tsx
  src/app/(protected)/driver/my-estimates/sent/page.tsx
  src/app/(protected)/driver/received-requests/_components/InputPrice.tsx
  src/app/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/app/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
  src/app/(protected)/driver/received-requests/_components/RequestCardList.tsx
  src/app/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/app/(protected)/driver/received-requests/page.tsx
  src/components/common/EstimateDetailInfo.tsx
  src/components/filter/FilterToggleButton.tsx
Labels: FE, UI

#84 [FEAT] 지정견적요청 API 연결
  src/app/(guest)/drivers/[id]/_components/BottomNav.tsx
  src/app/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
  src/app/(guest)/drivers/[id]/_components/EstimateRequestModal.tsx
  src/app/(guest)/drivers/[id]/_components/RequestEstimate.tsx
  src/app/(guest)/drivers/[id]/page.tsx
  src/app/(guest)/drivers/_components/Filters.tsx
  src/app/(guest)/drivers/_components/FindDrivers.tsx
  src/app/(guest)/drivers/_components/LikedDriverInfo.tsx
  src/app/(guest)/drivers/_components/LikedDrivers.tsx
  src/app/(guest)/drivers/page.tsx
  src/app/(protected)/driver/received-requests/page.tsx
  src/components/dropdown/FilterDropdown.tsx
  src/components/dropdown/SortDropdown.tsx
  src/lib/api/api-driver.ts
  src/lib/api/api-favorite.ts
  src/utills/TranslateFunction.tsx
Labels: Feature, FE

#85 [김다은] 대기 중인 견적 리스트 api 연동
  src/app/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/lib/api/api-myEstimate.ts
  src/types/estimateType.ts
  src/utills/addressUtils.ts
  src/utills/moveUtils.ts
Labels: FE, API

#90 [Fix] 리뷰 폴더 위치 변경 및 다국어 폴더 수정
  src/app/[locale]/(protected)/customer/review/_components/Main.tsx
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/NoReview.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewWrite.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/app/[locale]/(protected)/customer/review/page.tsx
  src/app/[locale]/review/component/EmptyReivew.tsx
  src/components/Header.tsx
  src/components/Pagination.tsx
  src/i18n/request.ts
  src/lib/api/api-3.ts
  src/lib/api/api-review.ts
  src/messages/en/Review.json
  src/messages/ko/Review.json
  src/messages/zh/Review.json
Labels: Fix, Refactor, FE

#93 [Feat 이지수] 소셜 로그인 구현 완료
  src/app/[locale]/(auth)/login/customer/page.tsx
  src/app/[locale]/(auth)/login/driver/page.tsx
  src/app/[locale]/(auth)/signup/customer/page.tsx
  src/app/[locale]/(auth)/signup/driver/page.tsx
Labels: Feature

#92 [Locale] 다국어 기능 랜딩과 리뷰에 적용
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewWrite.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/app/[locale]/landing/_component/ChangeImages.tsx
  src/app/[locale]/landing/_component/MovingCard.tsx
  src/app/[locale]/landing/page.tsx
  src/components/Header.tsx
  src/components/InputText.tsx
  src/components/chip/ChipRectangle.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/gnb/GnbMenuList.tsx
  src/components/notification/NotificationDropdown.tsx
  src/constant/constant.ts
  src/constant/moveDetails.ts
  src/constant/moveTypes.ts
  src/i18n/request.ts
  src/messages/en/Chip.json
  src/messages/en/Gnb.json
  src/messages/en/Landing.json
  src/messages/en/Review.json
  src/messages/ko/Chip.json
  src/messages/ko/Gnb.json
  src/messages/ko/Landing.json
  src/messages/ko/Review.json
  src/messages/zh/Chip.json
  src/messages/zh/Gnb.json
  src/messages/zh/Landing.json
  src/messages/zh/Review.json
  src/utills/dateUtils.tsx
  src/utills/moveUtils.ts
Labels: Feature, Refactor

#94 [FEAT] modal provider 및 dropdown 수정
  src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/EstimateRequestModal.tsx
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/app/[locale]/(protected)/driver/my-page/page.tsx
  src/components/driver/DriverReviews.tsx
  src/components/dropdown/FilterDropdown.tsx
  src/components/dropdown/SortDropdown.tsx
  src/providers/AuthProvider.tsx
  src/providers/ModalProvider.tsx
  src/providers/Providers.tsx
Labels: Fix, Refactor

#95 feat:견적요청 다국어
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/MoveTypeCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
  src/constant/moveTypes.ts
  src/i18n/request.ts
  src/messages/en/EstimateReq.json
  src/messages/ko/EstimateReq.json
  src/messages/ko/Landing.json
  src/messages/zh/EstimateReq.json
Labels: Feature

#96 feat: 기사님 찾기 다국어
  src/app/[locale]/(guest)/drivers/_components/Filters.tsx
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/app/[locale]/(guest)/drivers/_components/LikedDrivers.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/app/[locale]/common/page.tsx
  src/components/dropdown/FilterDropdown.tsx
  src/components/dropdown/SortDropdown.tsx
  src/i18n/request.ts
  src/messages/en/FindDriver.json
  src/messages/ko/FindDriver.json
  src/messages/zh/FindDriver.json
Labels: Feature, Refactor

#98 feat: 기사님 상세 다국어
  src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/EstimateRequestModal.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/FavoriteButton.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/RequestEstimate.tsx
  src/app/[locale]/(guest)/drivers/[id]/page.tsx
  src/app/[locale]/(guest)/drivers/page.tsx
  src/components/Service.tsx
  src/components/card/DriverFindCard.tsx
  src/components/driver/DriverReviews.tsx
  src/components/driver/DriverSimpleInfo.tsx
  src/messages/en/FindDriver.json
  src/messages/ko/FindDriver.json
  src/messages/zh/FindDriver.json
Labels: Feature, Refactor

#99 [FEAT] 기사님 기본정보 수정 페이지 UI 및 API 연결
  src/app/[locale]/(protected)/driver/my-page-edit/page.tsx
  src/app/[locale]/(protected)/driver/my-page/_components/EditButtons.tsx
  src/lib/api/api-profile.ts
Labels: Feature, UI, API

#100 [기능] 받은요청 페이지 프론트/백 연동
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/app/[locale]/common/page.tsx
  src/components/chip/ChipCircle.tsx
  src/components/filter/FilterModal.tsx
  src/components/filter/FilterSection.tsx
  src/lib/api/api-driver.ts
  src/types/request.ts
  src/utills/RequestMapper.tsx
Labels: Feature, FE

#104 Feat: 다국어 기사님 마이페이지, 받은 견적
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
  src/app/[locale]/(protected)/driver/my-page/_components/EditButtons.tsx
  src/app/[locale]/(protected)/driver/my-page/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/components/filter/FilterModal.tsx
  src/i18n/request.ts
  src/messages/en/DriverMypage.json
  src/messages/en/ReceivedReq.json
  src/messages/ko/DriverMypage.json
  src/messages/ko/ReceivedReq.json
  src/messages/zh/DriverMypage.json
  src/messages/zh/ReceivedReq.json
Labels: Refactor, FE

#105 locale: 기사님 마이페이지, 받은요청, 내 견적 다국어
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/components/chip/ChipConfirmed.tsx
  src/components/common/EstimateDetailInfo.tsx
  src/i18n/request.ts
  src/messages/en/MyEstimate.json
  src/messages/en/ReceivedReq.json
  src/messages/ko/MyEstimate.json
  src/messages/ko/ReceivedReq.json
  src/messages/zh/MyEstimate.json
  src/messages/zh/ReceivedReq.json
Labels: Feature, Refactor

#108 DevNav 삭제 요청
  src/app/[locale]/layout.tsx
  src/components/DevNav.tsx
  src/components/gnb/GnbMenuList.tsx
Labels: FE, UI

#109 [UI] 시맨틱 태그 적용 / 랜딩페이지 텍스트 포지션 2xl 해상도 대응
  src/app/[locale]/landing/page.tsx
  src/components/notification/NotificationDropdown.tsx
  src/components/notification/_components/NotificationItem.tsx
Labels: Refactor, FE, UI

#112 [Fix 이지수] 프로필 수정 생성 페이지 변경 및 새로운 auth 부분 새로운 api 추가
  src/app/[locale]/(protected)/customer/profile/edit/page.tsx
  src/app/[locale]/(protected)/customer/profile/page.tsx
  src/app/[locale]/(protected)/driver/my-page-edit/page.tsx
  src/app/[locale]/(protected)/driver/my-page/_components/EditButtons.tsx
  src/app/[locale]/(protected)/driver/profile/edit/page.tsx
  src/app/[locale]/(protected)/driver/profile/page.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/profile/CustomerProfileForm.tsx
  src/components/profile/DriverProfileForm.tsx
  src/components/profile/ImageUploader.tsx
  src/components/profile/ProfileForm.tsx
  src/constant/constant.ts
  src/constant/profile.ts
  src/lib/api/api-auth.ts
Labels: Fix

#113 [김다은] 찜한 기사님 데이터 연결 + 전체적인 디테일 점검
  public/assets/images/img_moving_car1.svg
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
  src/constant/moveTypes.ts
  src/types/favoriteType.ts
  src/utills/moveUtils.ts
Labels: Feature, API

#115 [FE] 페이지 이동 시 useTrasitionRouter 적용
  package-lock.json
  package.json
  src/app/[locale]/layout.tsx
  src/components/container/ConditionalTransitionWrapper.tsx
  src/components/container/PageTransitionWrapper.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/gnb/Gnb.tsx
  src/components/gnb/GnbMenuList.tsx
  src/components/gnb/_components/Logo.tsx
  src/hooks/useTransitionRouter.ts
Labels: Feature, FE, UI

#116 [FEAT] 고객 프로필 생성 UI
  public/assets/icons/ic_profile_upload.svg
  src/app/[locale]/(protected)/customer/profile/edit/page.tsx
  src/app/[locale]/(protected)/customer/profile/page.tsx
  src/components/chip/ChipCircle.tsx
  src/components/profile/CustomerProfileForm.tsx
  src/components/profile/ImageUploader.tsx
  src/components/profile/SelectRegion.tsx
  src/components/profile/SelectService.tsx
Labels: UI

#117 [기능] 보낸견적조회 API 연동
  src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/lib/api/api-driver.ts
  src/messages/en/MyEstimate.json
  src/messages/ko/MyEstimate.json
  src/messages/zh/MyEstimate.json
  src/types/estimateType.ts
Labels: Feature, FE

#120 Feat: review api 연동
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/lib/api/api-review.ts
Labels: Fix, Feature

#125 [기능] 반려요청 페이지 및 견적상세 페이지 API 연동
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedCardList.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/lib/api/api-driver.ts
  src/messages/ko/MyEstimate.json
  src/types/estimateType.ts
  src/utills/RequestMapper.tsx
  src/utills/dateUtils.tsx
Labels: Feature, FE

#127 [FIX] 토스트모달, 검색 오류 해결, 지정 견적요청 로딩추가
  src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/Toast.tsx
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/components/card/DriverFindCard.tsx
  src/messages/en/FindDriver.json
  src/messages/ko/FindDriver.json
  src/messages/zh/FindDriver.json
Labels: Fix

#128 Feat: 리뷰 생성, 삭제, 내가 쓴 리뷰 가져오기 API 연결 및 수정
  src/app/[locale]/(protected)/customer/review/_components/Main.tsx
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/NoMyReview.tsx
  src/app/[locale]/(protected)/customer/review/_components/NoReview.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewWrite.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/app/[locale]/(protected)/customer/review/page.tsx
  src/lib/api/api-review.ts
  src/messages/en/Review.json
  src/messages/ko/Review.json
  src/messages/zh/Review.json
Labels: Fix, Feature, FE, API

#129 Feat:리뷰 페이지네이션 연동, 컴포넌트 연동, 리액트 쿼리 적용
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/components/notification/NotificationDropdown.tsx
  src/lib/api/api-review.ts
Labels: Feature, FE, API

#131 [FIX] 지정견적요청 완료 바로 반영
  src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
Labels: Fix, UI

#135 [Fix/profileui 이지수] prifile UI 수정 및 로그인 페이지 상단 UI 수정
  src/app/[locale]/(auth)/login/customer/page.tsx
  src/app/[locale]/(auth)/login/driver/page.tsx
  src/components/profile/CustomerProfileCreateForm.tsx
  src/components/profile/CustomerProfileEditForm.tsx
  src/components/profile/DriverProfileForm.tsx
  src/components/profile/ImageUploader.tsx
Labels: Fix

#137 feat: 주소 검색 및 견적 요청 폼 UI/로직 개선
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/AddressResultCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/MoveTypeCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/DatePicker.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/dropdown/CalenderDropdown.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/DaumPostcodeModal.tsx
  src/app/[locale]/(protected)/customer/estimate-request/page.tsx
  src/hooks/useMediaQuery.ts
  src/types/Address.ts
Labels: Refactor, FE, UI

#136 [fix 이지수]기사 및 고객 수정 페이지 오류 해결
  src/components/Button.tsx
  src/components/profile/CustomerProfileEditForm.tsx
  src/components/profile/DriverProfileForm.tsx
Labels: Fix

#139 Fix: 견적 요청 시 moveType 전송 오류 수정
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
Labels: Fix

#140 [김다은] 토스트 모달 오류 수정
  src/app/[locale]/layout.tsx
  src/components/common-modal/ToastModal.tsx
Labels: Fix, FE

#138 [황수정] GNB 사이드 레이어 width 값 수정
  src/components/gnb/GnbMenuList.tsx
Labels: Fix, UI

#142 Feat: 로티 추가, 지정견적칩, 기사 이미지 연동
  package-lock.json
  package.json
  public/lottie/review-lottie.json
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/components/gnb/Gnb.tsx
  src/components/gnb/LanguageSwitcher.tsx
Labels: Feature, FE, API

#143 [FIX] 로딩 인디케이터 추가
  src/app/[locale]/(guest)/drivers/[id]/_components/RequestEstimate.tsx
  src/app/[locale]/(guest)/drivers/[id]/page.tsx
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/app/[locale]/(protected)/driver/my-page/page.tsx
  src/app/[locale]/common/page.tsx
  src/components/card/DriverFindCardSkeleton.tsx
  src/components/driver/DriverReviewSkeleton.tsx
  src/components/driver/DriverReviews.tsx
Labels: Fix, UI

#144 Feat:lottie 오류 수정
  src/app/[locale]/(guest)/drivers/[id]/_components/Toast.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
Labels: Fix

#146 fix: 주소 모달 번역키 누락문제 해결 및 토스트 알림 리팩토링
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
Labels: Fix, Refactor

#145 [김다은] 다국어 기능 추가 & 상세페이지 에러 해결
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/components/common/EstimateDetailInfo.tsx
  src/messages/en/MyEstimates.json
  src/messages/ko/MyEstimates.json
Labels: Fix

#147 [Refactor] 반응형 및 코드 개선
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedCardList.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateInfoSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/InputPrice.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/app/[locale]/common/page.tsx
  src/components/dropdown/SortDropdown.tsx
  src/constant/constant.ts
  src/constant/moveTypes.ts
  src/messages/en/ReceivedReq.json
  src/messages/ko/MyEstimate.json
  src/messages/ko/ReceivedReq.json
  src/types/estimateType.ts
  src/types/request.ts
  src/utills/RequestMapper.tsx
Labels: Refactor, FE

#148 Feat: lottie 컴포넌트로 뺌
  public/lottie/loadingLottie.json
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/components/lottie/LoadingLottie.tsx
Labels: Refactor, UI

#154 feat: 견적 요청 페이지 다국어 적용 및 Lottie 로딩 UI 개선
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/DisabledForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/AddressResultCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/MoveTypeCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/DatePicker.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/MobileDatePicker.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/dropdown/CalenderDropdown.tsx
  src/i18n/request.ts
  src/messages/en/Chip.json
  src/messages/en/Date.json
  src/messages/en/EstimateReq.json
  src/messages/ko/Chip.json
  src/messages/ko/Date.json
  src/messages/ko/EstimateReq.json
  src/messages/zh/Chip.json
  src/messages/zh/Date.json
  src/messages/zh/EstimateReq.json
  src/utills/dateUtils.tsx
Labels: Feature, Refactor, FE

#158 [Fix,Refactor 이지수] 로그인, middleware , AuthProvider 리팩토링
  src/app/[locale]/(auth)/login/customer/page.tsx
  src/app/[locale]/(auth)/login/driver/page.tsx
  src/components/profile/CustomerProfileEditForm.tsx
  src/hooks/useAuthForm.ts
  src/lib/api/api-auth.ts
  src/middleware.ts
  src/providers/AuthProvider.tsx
Labels: Fix, Refactor

#160 fix: 도로명 주소 빌딩명 중복 표시 문제 수정
  src/utills/AddressMapper.tsx
Labels: Fix
