Repository sebiny/6-moving-team2-FE, pull requests merged in 2025-08, with the labels that each got.

#163 [FIX] 기사님 상세 페이지 리뷰 에러 해결
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/app/[locale]/(guest)/drivers/page.tsx
  src/components/Pagination.tsx
  src/components/card/DriverFindCard.tsx
  src/components/driver/DriverReview.tsx
  src/components/driver/DriverReviews.tsx
  src/constant/constant.ts
  src/messages/en/FindDriver.json
  src/messages/ko/FindDriver.json
  src/messages/zh/FindDriver.json
  src/types/reviewType.ts
Labels: Fix

#164 Locale: my review
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/app/[locale]/(protected)/customer/review/page.tsx
  src/i18n/request.ts
  src/types/reviewType.ts
  src/utills/batchTranslate.ts
Labels: Feature, Refactor

#165 [김다은] 카카오톡 견적서 공유하기 기능 추가
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
Labels: Feature, FE

#169 [김다은] 카카오톡 견적서 공유하기 오류 수정
  src/app/[locale]/(guest)/drivers/[id]/page.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/hooks/useKakaoShare.ts
Labels: Fix, Feature

#172 [fix 이지수]로그아웃 삭제 모듈 clearAccessToken 변경
  src/lib/FetchClient.ts
Labels: Fix

#177 fix:배포오류
  src/app/[locale]/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
Labels: Fix

#179 Locale: driver 찾기, 받은견적
  src/app/[locale]/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/components/card/DriverFindCard.tsx
Labels: Feature

#178 [황수정] 기사님 / 받은 견적요청 request.createdAt DeepL 적용
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
Labels: FE, UI

#180 Locale: review 동적 다국어
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/EstimateDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/InputPrice.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/components/card/DriverFindCard.tsx
  src/components/common/EstimateDetailInfo.tsx
  src/messages/en/Common.json
  src/messages/ko/Common.json
  src/messages/zh/Common.json
Labels: FE

#183 feat:driver profile locale
  src/app/[locale]/(protected)/driver/my-page-edit/page.tsx
  src/app/[locale]/(protected)/driver/my-page/page.tsx
  src/components/profile/DriverProfileForm.tsx
  src/i18n/request.ts
  src/messages/en/DriverProfile.json
  src/messages/en/DriverProfileEdit.json
  src/messages/ko/DriverProfile.json
  src/messages/ko/DriverProfileEdit.json
  src/messages/zh/DriverProfile.json
  src/messages/zh/DriverProfileEdit.json
Labels: Feature, FE

#185 [fix 이지수 ]로그인 및 프로필 페이지 토스트모달 반영 및 토큰 도메인 설정값 .env로 변경
  src/app/[locale]/(auth)/login/customer/page.tsx
  src/app/[locale]/(auth)/login/driver/page.tsx
  src/components/profile/DriverProfileForm.tsx
  src/hooks/useAuthForm.ts
  src/lib/FetchClient.ts
  src/messages/en/Login.json
  src/messages/ko/DriverProfileEdit.json
  src/messages/ko/Login.json
  src/messages/zh/Login.json
  src/utills/getCookieDomain.ts
Labels: Fix

#188 [황수정] 로그인 버튼 다국어 관련 레이아웃 로직 수정
  src/components/gnb/GnbMenuList.tsx
Labels: Fix, UI

#189 [Fix/middleware 이지수] 소셜로그인 토스트 모달 추가 및 미들웨어 토큰 요청 로직 추가 및 name 유효성 검사 제거
  src/app/[locale]/(auth)/signup/customer/page.tsx
  src/app/[locale]/(auth)/signup/driver/page.tsx
  src/app/[locale]/(protected)/driver/my-page-edit/page.tsx
  src/app/[locale]/layout.tsx
  src/components/WelcomeToastTrigger.tsx
  src/hooks/useAuthForm.ts
  src/middleware.ts
Labels: Fix

#190 [황수정] 알림 다국어 적용 보완
  src/components/notification/NotificationDropdown.tsx
Labels: Fix, UI

#192 Locale: 주소 요약 번역에 DeepL 다국어 처리 적용 및 스크롤바 스타일 적용
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/DaumPostcodeModal.tsx
  src/app/globals.css
  src/components/Button.tsx
  src/messages/en/EstimateReq.json
  src/messages/ko/EstimateReq.json
  src/messages/zh/EstimateReq.json
  src/types/Address.ts
Labels: Refactor, FE, UI

#194 Locale: customer review
  src/app/[locale]/(guest)/drivers/_components/LikedDriverInfo.tsx
  src/components/driver/DriverReview.tsx
  src/messages/en/Login.json
Labels: Fix, FE

#197 fix: 프로필/견적 요청 페이지 로딩 다국어 누락 수정
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/[locale]/(protected)/customer/profile/edit/page.tsx
  src/messages/en/EstimateReq.json
  src/messages/en/Profile.json
  src/messages/ko/EstimateReq.json
  src/messages/ko/Profile.json
  src/messages/zh/EstimateReq.json
  src/messages/zh/Profile.json
Labels: FE, UI

#202 [황수정] 로그인버튼, 랜딩페이지 텍스트 포지션 조정
  src/app/[locale]/landing/_component/ChangeImages.tsx
  src/components/Button.tsx
  src/components/gnb/Gnb.tsx
Labels: FE, UI

#204 Style: modal error revise
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/components/InputText.tsx
Labels: UI

#205 [황수정] 기사님찾기 페이지에서 gnb 스타일링 수정
  src/components/gnb/Gnb.tsx
Labels: UI

#206 [김다은] QA 버그 수정 & 견적서 공유 페이지 디자인 수정
  src/app/[locale]/(protected)/customer/my-estimates/_components/SubHeader.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/EstimateDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
  src/app/[locale]/estimate/shared/[token]/page.tsx
  src/app/[locale]/toast/page.tsx
  src/components/common-modal/ToastModal.tsx
  src/components/common/EstimateDetailInfo.tsx
  src/components/gnb/Gnb.tsx
Labels: Fix, FE

#211 [fix: 이지수] 프로필 생성 토스트 다국어 모달 수정
  src/messages/en/DriverProfileEdit.json
  src/messages/zh/DriverProfileEdit.json
Labels: Fix

#217 refactor: 주소 정적 번역 비동기로 수정
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
  src/messages/en/EstimateReq.json
  src/messages/ko/EstimateReq.json
  src/messages/zh/EstimateReq.json
Labels: Refactor, FE, UI

#219 [김다은] 다국어 중국어 추가 & 견적서 공유용 페이지 디자인 수정
  src/app/[locale]/estimate/shared/[token]/page.tsx
  src/messages/zh/MyEstimate.json
  src/messages/zh/MyEstimates.json
Labels: Fix, FE

#218 [Fix] 견적조회, 반려요청 페이지 반응형 레이아웃 개선
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/AddressDateSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
Labels: FE, UI

#221 [UI] 기사님찾기 페이지 검색/필터/정렬 UI 개선 및 버그 수정
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/components/dropdown/FilterDropdown.tsx
  src/components/dropdown/SortDropdown.tsx
  src/components/input/SearchBar.tsx
Labels: Refactor, FE, UI

#222 [Fix] 견적 상세페이지 반응형 및 번역 오류 수정
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/messages/en/MyEstimate.json
  src/messages/zh/MyEstimate.json
Labels: FE, UI

#220 Fix: review
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewCost.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
Labels: Fix

#223 [FIX] favorite drivers
  src/app/[locale]/(guest)/drivers/_components/LikedDrivers.tsx
  src/app/[locale]/(protected)/driver/my-page/page.tsx
Labels: Fix

#224 Refactor: review
  src/app/[locale]/(protected)/customer/review/_components/Main.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
  src/app/[locale]/(protected)/customer/review/page.tsx
  src/app/[locale]/(protected)/customer/review/textLang.tsx
  src/types/reviewType.ts
Labels: Refactor

#226 [김다은] 좋아요 토글 버튼 추가
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/app/[locale]/estimate/shared/[token]/page.tsx
  src/components/Title.tsx
  src/types/estimateType.ts
Labels: Fix, Feature

#227 style: 탭 헤더 높이 및 기사찾기 카드 마진 레이아웃 수정
  src/app/[locale]/(guest)/drivers/_components/FindDrivers.tsx
  src/components/Header.tsx
Labels: FE, UI

#231 feat: 최대 3명 제한 에러메세지 토스트로 뜨도록 수정
  src/app/[locale]/(guest)/drivers/[id]/_components/DesignatedEstimateButton.tsx
Labels: FE, UI

#233 [김다은] 기능빠진 부분 수정
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/estimate/shared/[token]/page.tsx
Labels: Fix, FE

#234 [김다은] 시연 전 최종 수정..
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateInfoSection.tsx
  src/hooks/useFavoriteToggle.ts
Labels: Fix

#236 [김다은] 받았던 견적 하트 모양 조건 처리 & 견적 확정 모달 text 버그 수정
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
Labels: Fix, FE

#238 [황수정] gnb 리팩토링
  src/components/gnb/Gnb.tsx
Labels: Refactor

#239 [황수정] gnb 메뉴 애니메이션 효과 적용
  src/components/gnb/GnbListLayout.tsx
  src/components/gnb/GnbMenuList.tsx
Labels: Fix, UI

#241 [Refactor] 견적요청 페이지, 컴포넌트 UI 및 접근성 개선
  src/app/[locale]/(protected)/customer/estimate-request/DesktopEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/DisabledForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/MobileEstimateForm.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/AddressResultCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/card/MoveTypeCard.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/DatePicker.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/datepicker/MobileDatePicker.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/dropdown/CalenderDropdown.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/AddressCardModal.tsx
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/DaumPostcodeModal.tsx
Labels: Refactor, FE, UI

#242 [김다은] 내견적관리 & 찜한 기사님 부분 웹 접근성 개선
  src/app/[locale]/(protected)/customer/my-estimates/MyEstimate.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/PastDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/[id]/_components/AutoRejectedAlert.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/EstimateDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimate.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/_components/ReceivedEstimateData.ts
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingData.ts
  src/app/[locale]/(protected)/customer/my-estimates/favorite-drivers/FavoriteDrivers.tsx
  src/app/[locale]/estimate/shared/[token]/page.tsx
  src/app/[locale]/toast/page.tsx
  src/components/Button.tsx
  src/components/OrangeBackground.tsx
  src/components/ShareDriver.tsx
  src/components/Title.tsx
  src/components/common-modal/AlertModal.tsx
  src/components/common-modal/ToastModal.tsx
  src/components/common/EstimateDetailInfo.tsx
  src/components/lottie/LoadingLottie.tsx
Labels: Refactor, FE

#245 [김다은] ui 수정
  src/app/[locale]/(protected)/customer/my-estimates/MyEstimate.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-past/PastEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
Labels: Fix, FE

#246 [FIX] 기사님 상세 수정
  src/app/[locale]/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/FavoriteButton.tsx
  src/app/[locale]/(guest)/drivers/[id]/page.tsx
  src/app/[locale]/(protected)/driver/my-page/page.tsx
  src/components/OrangeBackground.tsx
  src/components/card/DriverFindCard.tsx
  src/components/driver/DriverReviews.tsx
  src/components/driver/DriverSimpleInfo.tsx
  src/components/icon/DrawingIcon.tsx
  src/components/input/SearchBar.tsx
  src/messages/en/DriverMypage.json
  src/messages/en/FindDriver.json
  src/messages/ko/DriverMypage.json
  src/messages/ko/FindDriver.json
  src/messages/zh/DriverMypage.json
  src/messages/zh/FindDriver.json
Labels: Fix, Refactor, FE

#247 [황수정] gnb 리팩토링
  src/app/[locale]/landing/_component/ChangeImages.tsx
  src/components/dropdown/ProfileDropdown.tsx
  src/components/gnb/Gnb.tsx
  src/components/gnb/GnbListLayout.tsx
  src/components/gnb/GnbMenuList.tsx
  src/components/notification/NotificationDropdown.tsx
  src/hooks/useGnbHook.ts
Labels: Refactor, FE

#249 [feat 이지수]:s3앞에 클라우드 프론트 추가
  next.config.ts
Labels: Feature

#250 [Improve] 주요 페이지 웹접근성 개선 및 로딩/토스트 처리 수정
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/RejectedCardList.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateInfoSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/AddressDateSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CompletedEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/EstimateCardList.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/InputPrice.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/RequestCardList.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/components/dropdown/SortDropdown.tsx
  src/components/input/SearchBar.tsx
  src/messages/en/MyEstimate.json
  src/messages/ko/MyEstimate.json
  src/messages/zh/MyEstimate.json
Labels: FE

#252 [김다은] ui 4차 수정
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/estimate/shared/[token]/page.tsx
Labels: Fix, UI

#254 [황수정] ogImage 반영
  public/og-image.webp
  src/app/[locale]/layout.tsx
Labels: Chore

#257 [Feat] 기사/견적 상세 페이지 성능 최적화
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateHeaderSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/_components/EstimateInfoSection.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/components/ShareDriver.tsx
Labels: Feature, FE

#258 og이미지 수정, gnb 코드 수정
  public/og-image.webp
  src/app/[locale]/layout.tsx
  src/components/gnb/Gnb.tsx
Labels: Fix

#255 Fix:review error
  package-lock.json
  package.json
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/lib/api/api-review.ts
  src/messages/en/Review.json
  src/messages/ko/Review.json
  src/messages/zh/Review.json
  src/types/reviewType.ts
Labels: Fix

#261 [Feat] 견적상세페이지 로딩수정
  src/app/[locale]/(protected)/driver/my-estimates/sent/[id]/page.tsx
  src/components/loading/LoadingAnimation.tsx
Labels: FE, UI

#263 [황수정] gnb/profileDropdown 롤백
  src/components/dropdown/ProfileDropdown.tsx
  src/components/gnb/Gnb.tsx
  src/components/gnb/GnbListLayout.tsx
  src/components/gnb/GnbMenuList.tsx
  src/components/gnb/_components/Logo.tsx
  src/hooks/useGnbHook.ts
  src/hooks/useTransitionRouter.ts
Labels: Fix

#265 [FIX] 기사님 상세페이지 모바일 수정
  src/app/[locale]/(guest)/drivers/[id]/_components/DriverInfo.tsx
  src/app/[locale]/(guest)/drivers/[id]/_components/FavoriteButton.tsx
  src/components/ShareDriver.tsx
  src/components/card/DriverFindCard.tsx
  src/components/chip/ChipRectangle.tsx
  src/components/driver/DriverReviews.tsx
Labels: Fix, UI

#267 fix: 리뷰 불러오는 중일 때 스켈레톤
  src/components/driver/DriverReviews.tsx
Labels: Fix

#268 Fix: review error 및 리뷰 삭제 확인 모달 추가
  src/app/[locale]/(protected)/customer/review/_components/DeleteConfirmModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewWrite.tsx
Labels: Fix, Feature

#275 fix: aria-label 오류 수정
  src/app/[locale]/(protected)/customer/estimate-request/_components/modal/DaumPostcodeModal.tsx
Labels: Fix, FE

#273 Fix/review error
  src/app/[locale]/(protected)/customer/review/_components/DeleteConfirmModal.tsx
Labels: Fix

#281 Locale:review received esti
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
Labels: Fix

#282 [fix] 드라이버 페이지 로딩 일관화
  src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/app/[locale]/common/page.tsx
Labels: Fix, FE

#283 fix:deepL수정
  package-lock.json
  src/app/[locale]/(protected)/customer/review/_components/ModalContent.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
Labels: Fix

#284 [fix] 동적다국어 백API 연결
  src/app/[locale]/(protected)/driver/my-estimates/rejected/_components/CompletedRejectedCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/rejected/page.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/app/[locale]/(protected)/driver/my-estimates/sent/page.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/ReceivedRequestCard.tsx
  src/app/[locale]/(protected)/driver/received-requests/page.tsx
  src/utills/translateWithDeepL.ts
Labels: Fix, FE

#285 feat: review
  src/app/[locale]/(protected)/customer/review/_components/DeleteConfirmModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/MyReviews.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
  src/app/[locale]/(protected)/customer/review/_components/WritableReviews.tsx
Labels: Fix

#286 [김다은] 버그 6차 수정
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/PendingEstimates.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/[id]/PendingDetail.tsx
  src/app/[locale]/(protected)/customer/my-estimates/estimate-pending/_components/PendingCard.tsx
  src/app/[locale]/(protected)/customer/review/_components/ReviewModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/RejectEstimateModal.tsx
  src/app/[locale]/(protected)/driver/received-requests/_components/SendEstimateModal.tsx
  src/hooks/useUnsavedGuard.ts
  src/hooks/useUnsavedGuard.tsx
  src/lib/api/api-myEstimate.ts
  src/messages/en/Common.json
  src/messages/ko/Common.json
Labels: Fix, FE

#287 fix: 번역 요청 경로 오류 수정
  src/app/[locale]/(protected)/driver/my-estimates/sent/_components/CustomerEstimateCard.tsx
  src/hooks/useTranslate.ts
Labels: Fix

#289 Locale/review received esti
  src/utills/translateWithDeepL.ts
Labels: Fix

#290 fix: 다국어 요청 주소 수정
  src/app/[locale]/(protected)/customer/review/_components/ReviewsInner.tsx
Labels: Fix
